name: tfm
channels:
  - conda-forge
dependencies:
  - python=3.9
  # Análisis de datos
  - numpy=1.23.3
  - pandas=2.1.4
  - scipy=1.11.4
  - scikit-learn=1.6.1
  # Visualización y reducción de dimensionalidad
  - matplotlib=3.8.2
  - umap-learn=0.5.12
  # Interfaz web
  - streamlit=1.50.0
  # Notebook
  - notebook
  - ipykernel=6.31.0
